# Generated by Django 5.1.1 on 2024-09-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=255, verbose_name="Описание"
                    ),
                ),
                ("cost", models.IntegerField(verbose_name="Цена")),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукт",
            },
        ),
    ]
